### ISSUE TITLE
RuntimeError: input has inconsistent input_size: got 8 expected 16

### ISSUE THREAD

**Issue by MachRepo** [muditbhargava66/PyxLSTM#10]
I was testing the module using this code :
```
from xLSTM.model import xLSTM
import torch
model = xLSTM(5, 8, 16, 5, 2, 0.1, True, 'slstm')
inputs = torch.randint(low=0, high=5,size=(12,15000))
outputs = model(inputs)
```
when I set number of heads > 1 I get this error :
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bkffadia/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bkffadia/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/d/pyxLSTM/xLSTM/model.py", line 31, in forward
    output_seq, hidden_state = block(output_seq, hidden_states[i])
  File "/home/bkffadia/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bkffadia/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/d/pyxLSTM/xLSTM/block.py", line 55, in forward
    lstm_output, hidden_state = self.lstm(input_seq, hidden_state)
  File "/home/bkffadia/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bkffadia/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/d/pyxLSTM/xLSTM/slstm.py", line 47, in forward
    h, c = lstm(x, (hidden_state[a][0], hidden_state[a][1]))
  File "/home/bkffadia/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bkffadia/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bkffadia/.local/lib/python3.10/site-packages/torch/nn/modules/rnn.py", line 1347, in forward
    ret = _VF.lstm_cell(
RuntimeError: input has inconsistent input_size: got 8 expected 16
```

**Comment by muditbhargava66** [comment]
I will investigate this issue and provide a fix in the upcoming code update. In the meantime, I appreciate your patience and understanding. Please feel free to open a new issue or provide additional details if needed.

Best regards,
Mudit B.
