### ISSUE TITLE
unit tests as per README fail

### ISSUE THREAD

**Issue by jabowery** [muditbhargava66/PyxLSTM#24]
The unit tests as per `README.md` fail with this installation procedure:

```
$ cat environment.yml 
name: xlstm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
$ mamba env create -f environment.yml
$ pip install -r requirements.txt
```
On `Ubuntu 22.04.4 LTS`
With `NVIDIA Server Driver metapackage from nvidia-driver-535-server (proprietary)`

Then, as per [this closed issue regarding setup.py](https://github.com/muditbhargava66/PyxLSTM/issues/6#issuecomment-2116620834):

```
$ pip install .
Successfully installed PyxLSTM-1.0.1
$ python -m unittest discover tests
EEEEEEEEE
======================================================================
ERROR: test_backward_pass (test_block.TestXLSTMBlock.test_backward_pass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jabowery/devel/xlstm/tests/test_block.py", line 37, in test_backward_pass
    output_seq, _ = xlstm_block(input_seq)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/devel/xlstm/xLSTM/block.py", line 55, in forward
    lstm_output, hidden_state = self.lstm(input_seq, hidden_state)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/devel/xlstm/xLSTM/slstm.py", line 53, in forward
    if i < self.num_layers - 1:
       ^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Boolean value of Tensor with more than one value is ambiguous

======================================================================
ERROR: test_forward_pass_mlstm (test_block.TestXLSTMBlock.test_forward_pass_mlstm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jabowery/devel/xlstm/tests/test_block.py", line 27, in test_forward_pass_mlstm
    output_seq, hidden_state = xlstm_block(input_seq)
                               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/devel/xlstm/xLSTM/block.py", line 55, in forward
    lstm_output, hidden_state = self.lstm(input_seq, hidden_state)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/devel/xlstm/xLSTM/mlstm.py", line 68, in forward
    C_t = f * C + i * torch.matmul(values.unsqueeze(2), keys.unsqueeze(1)).squeeze(1)
          ~~^~~
RuntimeError: The size of tensor a (4) must match the size of tensor b (64) at non-singleton dimension 1

======================================================================
ERROR: test_forward_pass_slstm (test_block.TestXLSTMBlock.test_forward_pass_slstm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jabowery/devel/xlstm/tests/test_block.py", line 17, in test_forward_pass_slstm
    output_seq, hidden_state = xlstm_block(input_seq)
                               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/devel/xlstm/xLSTM/block.py", line 55, in forward
    lstm_output, hidden_state = self.lstm(input_seq, hidden_state)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/devel/xlstm/xLSTM/slstm.py", line 53, in forward
    if i < self.num_layers - 1:
       ^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Boolean value of Tensor with more than one value is ambiguous

======================================================================
ERROR: test_backward_pass (test_mlstm.TestMLSTM.test_backward_pass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jabowery/devel/xlstm/tests/test_mlstm.py", line 27, in test_backward_pass
    output_seq, _ = mlstm(input_seq)
                    ^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/devel/xlstm/xLSTM/mlstm.py", line 68, in forward
    C_t = f * C + i * torch.matmul(values.unsqueeze(2), keys.unsqueeze(1)).squeeze(1)
          ~~^~~
RuntimeError: The size of tensor a (4) must match the size of tensor b (64) at non-singleton dimension 1

======================================================================
ERROR: test_forward_pass (test_mlstm.TestMLSTM.test_forward_pass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jabowery/devel/xlstm/tests/test_mlstm.py", line 17, in test_forward_pass
    output_seq, hidden_state = mlstm(input_seq)
                               ^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/devel/xlstm/xLSTM/mlstm.py", line 68, in forward
    C_t = f * C + i * torch.matmul(values.unsqueeze(2), keys.unsqueeze(1)).squeeze(1)
          ~~^~~
RuntimeError: The size of tensor a (4) must match the size of tensor b (64) at non-singleton dimension 1

======================================================================
ERROR: test_backward_pass (test_model.TestXLSTMModel.test_backward_pass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jabowery/devel/xlstm/tests/test_model.py", line 29, in test_backward_pass
    output_seq, _ = xlstm_model(input_seq)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/devel/xlstm/xLSTM/model.py", line 39, in forward
    output_seq, hidden_state = block(output_seq, hidden_states[i])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/devel/xlstm/xLSTM/block.py", line 55, in forward
    lstm_output, hidden_state = self.lstm(input_seq, hidden_state)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/devel/xlstm/xLSTM/slstm.py", line 53, in forward
    if i < self.num_layers - 1:
       ^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Boolean value of Tensor with more than one value is ambiguous

======================================================================
ERROR: test_forward_pass (test_model.TestXLSTMModel.test_forward_pass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jabowery/devel/xlstm/tests/test_model.py", line 20, in test_forward_pass
    output_seq, hidden_states = xlstm_model(input_seq)
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/devel/xlstm/xLSTM/model.py", line 39, in forward
    output_seq, hidden_state = block(output_seq, hidden_states[i])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/devel/xlstm/xLSTM/block.py", line 55, in forward
    lstm_output, hidden_state = self.lstm(input_seq, hidden_state)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/devel/xlstm/xLSTM/slstm.py", line 53, in forward
    if i < self.num_layers - 1:
       ^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Boolean value of Tensor with more than one value is ambiguous

======================================================================
ERROR: test_backward_pass (test_slstm.TestSLSTM.test_backward_pass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jabowery/devel/xlstm/tests/test_slstm.py", line 27, in test_backward_pass
    output_seq, _ = slstm(input_seq)
                    ^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/devel/xlstm/xLSTM/slstm.py", line 53, in forward
    if i < self.num_layers - 1:
       ^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Boolean value of Tensor with more than one value is ambiguous

======================================================================
ERROR: test_forward_pass (test_slstm.TestSLSTM.test_forward_pass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jabowery/devel/xlstm/tests/test_slstm.py", line 17, in test_forward_pass
    output_seq, hidden_state = slstm(input_seq)
                               ^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/mambaforge/envs/xlstm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jabowery/devel/xlstm/xLSTM/slstm.py", line 53, in forward
    if i < self.num_layers - 1:
       ^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Boolean value of Tensor with more than one value is ambiguous

----------------------------------------------------------------------
Ran 9 tests in 0.044s

FAILED (errors=9)

```

**Comment by muditbhargava66** [comment]
The issue has been definitively resolved in the latest update, Version 2.0.0.
